app:
    resource: "@AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    # resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin